Init
Doooodie/rs-clone-backend pull request #2
Opened 2023-02-12 23:09 UTC by eys-man

- added database models according to schema
![image](https://user-images.githubusercontent.com/112211574/218342699-1abe1259-f89a-4e48-b86e-d76640e15a43.png)
- routing has been implemented;
- add error handling;
- adding a file to the database has been implemented

2023-02-13 22:54 UTC, Doooodie requested changes
Кроме всего прочего, необходимо удалить неиспользуемые картинки из директории `public`

2023-02-13 22:54 UTC, Doooodie commented on controllers/access-controller.js
> +        // console.log('user-controller: check');
В ветке `develop` не должно оставаться комментариев (только в крайних случаях и только на английском) и тем более логов в консоль

2023-02-13 22:54 UTC, Doooodie commented on controllers/comment-controller.js
> +        // console.log('user-controller: check');
Убрать комментарии

2023-02-13 22:54 UTC, Doooodie commented on controllers/file-controller.js
> +            // const imageFile = await file.create({ name, size, info, img: fileName, userId });
Убрать комментарии

2023-02-13 22:54 UTC, Doooodie commented on controllers/file-controller.js
> +            console.log('name = ' + name + ', size = ' + size + ', info = ' + info + ', userId = ' + userId);
Убрать логгирование. Если нужно оставить - поменять написание на косые кавычки, например `name = ${name}, size = ${size}`

2023-02-13 22:54 UTC, Doooodie commented on controllers/user-controller.js
> +        // res.json({ message: 'user-controller: login'});
Убрать комментарии

2023-02-13 22:54 UTC, Doooodie commented on error/api-error.js
> +export default ApiError;
В конце каждого файла должна быть пустая строчка. Чтобы не добавлять их вручную, поставь себе EditorConfig в VSCode и настрой его

2023-02-14 22:35 UTC, Doooodie requested changes

2023-02-14 22:35 UTC, Doooodie commented on models/models.js
> +        unique: false
В одном файле разные стили написания висячих запятых. Нужно выбрать один стиль и придерживаться его

2023-02-15 06:58 UTC, LineCoran approved these changes
Good job!!!!

2023-02-15 08:09 UTC, eys-man commented on models/models.js
> +        unique: false
поправил. сделал все висящими

2023-02-15 13:40 UTC, Doooodie approved these changes

2023-02-15 13:42 UTC, merged